# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[tool.ruff]
line-length = 88
exclude = [
    "__init__.py",
]

[tool.ruff.lint]
ignore = [
    "E203",
]

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = [
    "F401",
    "F841",
]
